### ISSUE TITLE
Crashes on startup of frontend 

### ISSUE THREAD

**Issue by looneym** [mskcc-clinbx/python-jwt-react-login-flow#2]
```
 ~/python-jwt-react-login-flow/app   master±  npm install
npm WARN python-jwt-react-login-flow@1.0.0 No repository field.

up to date in 4.314s
 ~/python-jwt-react-login-flow/app   master±  npm run dev

> python-jwt-react-login-flow@1.0.0 dev /Users/looneym/python-jwt-react-login-flow
> node build/start-dev

module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/looneym/python-jwt-react-login-flow/build/start-dev'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! python-jwt-react-login-flow@1.0.0 dev: `node build/start-dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the python-jwt-react-login-flow@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/looneym/.npm/_logs/2017-12-28T21_25_32_137Z-debug.log

```

**Comment by aarondack** [comment]
Thanks for pointing this out! I pushed up a commit that moved the `package.json` into the `app` folder where it should have been.
